name: Efficient Workflow

on: pull_request

jobs:
  run-hooks:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.10'

    - name: Install pre-commit
      run: pip install pre-commit

    - name: Set up hooks
      run: pre-commit install --hook-type pre-commit

    - name: Run pre-commit on all files
      run: pre-commit run --all-files

  run-unit-tests:
    runs-on: ubuntu-latest
    needs: run-hooks

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.10'
        cache: 'pip'

    - name: Install requirements
      run: pip install -r requirements.txt

    - name: Run unit tests
      run: python -m unittest discover tests/unit

  run-integration-tests:
    runs-on: ubuntu-latest
    needs: run-hooks

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.10'
        cache: 'pip'

    - name: Install requirements
      run: pip install -r requirements.txt

    - name: Run integration tests
      run: python -m unittest discover tests/integration
